global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'primary-db'
    static_configs:
      - targets: ['primary-db:5000']
    metrics_path: '/metrics'

  - job_name: 'backup-db'
    static_configs:
      - targets: ['backup-db:5000']
    metrics_path: '/metrics'

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
    